### PR TITLE
LRDOCS-1086 Wrote Geolocating Assets UserGuide doc and renumbered tutorials.

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sergiogonzalez can you review these UserGuide doc and let me know if anything needs updated?

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @mwilliams2014 the documentation looks good but I think that it might be good to include a few more things. For example:
- We provide 2 Maps provider: Google Maps and Open Street Maps. That can be configured in Portal Settings and Site Settings in the Advanced section. 
- The location is not necessarily set based on the current address of the user creating the content. They can type a specific address or even drag the indicator and drop it in any point in the map and the address will be automatically updated to reflect the new point.
- In the case of web content, once we have created the Web Content Structure, a new Web Content Template can be easily created because we provide a snippet that makes it very easy to display the location stored in the web content.

Let me know if you have any question or if you want me to take a look at something else.

Thanks!

**Comment by mwilliams2014** [comment]
Thanks @sergiogonzalez ! Can you elaborate on how the snippet works for the template?
Also I am not able to type my address in the map provider for the structure. It just allows me to share my location or not share my location.

**Comment by sergiogonzalez** [comment]
Basically, if you click on the geolocation field when adding the template the snippet will be automatically included in the template as you can see in the attachment. That snippet renders the geolocation in a map using the provider defined in the Portal/Site Settings (google maps or openstreet map)

image

**Comment by mwilliams2014** [comment]
Thanks! And as far as entering the address in the search bar, it looks like my build was a little outdated. I see that, that feature is on master. I'll make these updates and send it to be published.

**Pull request closed without merging**
